version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - store_artifacts:
          path: target/site/jacoco-aggregate/index.html
      - codecov/upload:
          file: ./target/site/jacoco-aggregate/index.html

workflows:
  build-and-test-project:
    jobs:
      - build
